### ISSUE TITLE
Copying Assignment

### ISSUE THREAD

**Issue by edhubc** [ubc/compair#1046] opened 2023-03-02 19:57 UTC
Instructor would like to see feature that allows an assignment to be copied within one ComPAIR course or copied to another ComPAIR course. Currently that is not possible, only the entire ComPAIR can be duplicated. Please see Service Now ticket: INC3272691.

**Comment by lenglund** [comment] 2023-03-02 22:24
Duplicate of https://github.com/ubc/compair/issues/883

**Closed by lenglund** 2023-03-02 22:24 UTC
